version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /src/tools/recommended/mcp/ospo-reframe
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /src/tools/recommended/mcp/ospo-pigeon-profile
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /src/tools/recommended/mcp/ospo-db
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
